### ISSUE TITLE
Node on Rpi fails 

### ISSUE THREAD

**Issue by mvadrev** [RedKenrok/node-hotworddetector#3]
**Description**: *Write a concise description of what problem you encountered.*

I installed all dependencies and am using node 13 on a raspberrypi 3. Here is my code. I initally did this on my Ubuntu PC and it works wonderfully. So, I created a new app with npm init --y and installed node audio recorder, placed the resources folder and used the same code as in the below github link. But I keep getting this error. Can you please help me?

HotwordDetector: Initialized.
AudioRecorder: Started recording.
HotwordDetector: Started detecting.
AudioRecorder: Exit code '1'.

https://github.com/mvadrev/nodehotword 

**Write any additional context in place of this.**

**Comment by RedKenrok** [comment]
Can you confirm that the external audio library is installed and working properly, either [SoX](sox.sourceforge.net/Docs/Documentation) or [Arecord](https://linux.die.net/man/1/arecord). If that is working correctly then clone, install and run the examples of [node-audiorecorder](https://github.com/RedKenrok/node-audiorecorder). Making sure everything underlying it is working will narrow down the problem.

**Comment by mvadrev** [comment]
Hey Man,

Thank for your reply. Turns out asoundrc config was the problem. The output was device 0 id 0 and output was 0 and 1. Thanks. Closing this

**Comment by mvadrev** [comment]
Thanks for the amazing lib

**Comment by RedKenrok** [comment]
Thank you for the quick response and best of luck with your project.
